In [105]:
#numpy

import numpy as np
#import numpy

a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4, 5, 6]])
print(a,a.shape)
print(b,b.shape)
a[2] = 10
print(a)
print(a.ndim, b.ndim)
print(a.size,b.size)
print(a.dtype,b.dtype)

c = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print(c,c.dtype)

d = np.zeros((3,4))
print(d)
e = np.ones((2,2,2),dtype=np.int16)
print(e)

f = np.empty((1,2))
print(f) # garbage values

g = np.arange(4)
print(g)

g = np.arange(4,9,2)
print(g)


h = np.linspace(0, 10, 5) # np.linspace(0, 10, num=5) is the same
print(h)

i = np.random.random((2,2))
print(i)

[1 2 3] (3,)
[[1 2 3]
 [4 5 6]] (2, 3)
[ 1  2 10]
1 2
3 6
int64 int64
[[1. 2. 3.]
 [4. 5. 6.]] float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[1.39069238e-309 1.39069238e-309]]
[0 1 2 3]
[4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[0.20070097 0.0112599 ]
 [0.96635478 0.68219806]]


In [106]:
a = np.array([[1, 4], [3, 1]])
print(a,end="\n\n")
print(np.sort(a, axis=1), end="\n\n") # sort along the first axis


a1 = np.array([[1, 4], [3, 1]])
a2 = np.array([[1, 2], [3, 4]])
print(np.concatenate((a1, a2), axis=0)) # concatenate along the first axis
print(np.concatenate((a1, a2), axis=1)) # concatenate along the second axis
print()

print(np.vstack((a1, a2))) # vertical stack
print(np.hstack((a1, a2))) # horizontal stack

c = np.arange(100)
c = c.reshape(10,10)
print(c,end="\n\n")


d = np.array([1,2,3,4,5,6])
d = d[np.newaxis, :]
print(d, d.shape,end="\n\n")

d = np.array([1,2,3,4,5,6])
d = d[:, np.newaxis]
print(d, d.shape,end="\n\n")

[[1 4]
 [3 1]]

[[1 4]
 [1 3]]

[[1 4]
 [3 1]
 [1 2]
 [3 4]]
[[1 4 1 2]
 [3 1 3 4]]

[[1 4]
 [3 1]
 [1 2]
 [3 4]]
[[1 4 1 2]
 [3 1 3 4]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[1 2 3 4 5 6]] (1, 6)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)



In [107]:
a = np.arange(10)
print(a[2:5]) 
print(a[2:])  
print(a[:5])  
print(a[-1])  

print(a[2:5:2])

print(a[::-1])

print(a[a%2==0])

print(a[(a>2) & (a<8)])
x = lambda l : l%5>=4
print(a[x(a)])



[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4]
9
[2 4]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]
[3 4 5 6 7]
[4 9]


In [108]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean())
print(a.mean(axis=0))
print(a.prod())
print(a.prod(axis=0))
print(a.transpose())
print(a.T)
print(a.flatten())
print(a.ravel())
print(a.max())
print(a.max(axis=0))
print(a.min())
print(a.min(axis=0))
print(a.argmax())
print(a.argmin())

b = np.array([[1, 2,2,3], [3, 4,3,2]])
print(np.unique(b))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
5.5
[4. 5. 6. 7.]
0
[  0  45 120 231]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
[ 8  9 10 11]
0
[0 1 2 3]
11
0
[1 2 3 4]


In [109]:
a = np.array([[1,2,3],[4,5,6], [9,8,3]])
b = np.array([[7,8,9],[10,11,12], [13,14,15]])
print(np.dot(a,b))
print(a @ b) # same as np.dot(a,b)
print(np.matmul(a,b)) # same as np.dot(a,b)
print(np.inner(a,b)) # inner product of a and b
print(np.outer(a,b)) # outer product of a and b
print(np.cross(a,b)) # cross product of a and b
print(np.linalg.det(a)) # determinant of a
print(np.linalg.inv(a)) # inverse of a
print(np.linalg.eig(a)) # eigenvalues and eigenvectors of a
print(np.linalg.svd(a)) # singular value decomposition of a
print(np.linalg.norm(a)) # Frobenius norm of a
print(np.linalg.matrix_rank(a)) # rank of a
print(np.linalg.solve(a,b)) # solve the linear equation ax = b
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(a*1.6)

[[ 66  72  78]
 [156 171 186]
 [182 202 222]]
[[ 66  72  78]
 [156 171 186]
 [182 202 222]]
[[ 66  72  78]
 [156 171 186]
 [182 202 222]]
[[ 50  68  86]
 [122 167 212]
 [154 214 274]]
[[  7   8   9  10  11  12  13  14  15]
 [ 14  16  18  20  22  24  26  28  30]
 [ 21  24  27  30  33  36  39  42  45]
 [ 28  32  36  40  44  48  52  56  60]
 [ 35  40  45  50  55  60  65  70  75]
 [ 42  48  54  60  66  72  78  84  90]
 [ 63  72  81  90  99 108 117 126 135]
 [ 56  64  72  80  88  96 104 112 120]
 [ 21  24  27  30  33  36  39  42  45]]
[[ -6  12  -6]
 [ -6  12  -6]
 [ 78 -96  22]]
12.000000000000005
[[-2.75        1.5        -0.25      ]
 [ 3.5        -2.          0.5       ]
 [-1.08333333  0.83333333 -0.25      ]]
EigResult(eigenvalues=array([13.50768467, -0.20654605, -4.30113863]), eigenvectors=array([[-0.27461747, -0.58171284, -0.32796011],
       [-0.63705854,  0.76509695, -0.40845631],
       [-0.72023722, -0.27611019,  0.85182487]]))
SVDResult(U=array([[-0.21157851, -0.46115915, -0.861

In [110]:
a = np.array([[1,2,3],[4,5,6]])
np.save('a.npy', a)
b = np.load('a.npy')
np.savetxt('a.csv', a, delimiter=',')
c = np.loadtxt('a.csv', delimiter=',')
